apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: user-challenges-deployment
spec:
  selector:
    matchLabels:
      app: user-challenges
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: user-challenges
    spec:
      containers:
      - name: user-challenges
        image: ancina/user-challenges:latest
        ports:
        - containerPort: 8088
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: user-challenges
spec:
  type: NodePort
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: user-challenges
